Failure # 1 (occurred at 2023-05-25_11-39-04)
[36mray::ImplicitFunc.train()[39m (pid=3427096, ip=129.241.113.29, repr=hyper_search_train)
  File "/lhome/oskarsto/repos/master-eeg-trans/.venv/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 384, in train
    raise skipped from exception_cause(skipped)
  File "/lhome/oskarsto/repos/master-eeg-trans/.venv/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 336, in entrypoint
    return self._trainable_func(
  File "/lhome/oskarsto/repos/master-eeg-trans/.venv/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 653, in _trainable_func
    output = fn()
  File "/lhome/oskarsto/repos/master-eeg-trans/.venv/lib/python3.8/site-packages/ray/tune/trainable/util.py", line 421, in _inner
    return inner(config, checkpoint_dir=None)
  File "/lhome/oskarsto/repos/master-eeg-trans/.venv/lib/python3.8/site-packages/ray/tune/trainable/util.py", line 413, in inner
    return trainable(config, **fn_kwargs)
  File "/lhome/oskarsto/repos/master-eeg-trans/DECCaTNet/DECCaTNet_model/hyper_search.py", line 144, in hyper_search_train
    cf.pre_train_model(copy.deepcopy(all_params), global_params)
  File "/lhome/oskarsto/repos/master-eeg-trans/DECCaTNet/DECCaTNet_model/contrastive_framework.py", line 437, in pre_train_model
    model, counter, epoch_loss = train_epoch(model, epoch, max_epochs, train_loader, device, optimizer, loss_func,
  File "/lhome/oskarsto/repos/master-eeg-trans/DECCaTNet/DECCaTNet_model/contrastive_framework.py", line 250, in train_epoch
    x1_encoded, x2_encoded = model(x1), model(x2)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/lhome/oskarsto/repos/master-eeg-trans/DECCaTNet/DECCaTNet_model/DECCaTNet_model.py", line 16, in forward
    x = self.projector(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/lhome/oskarsto/repos/master-eeg-trans/DECCaTNet/DECCaTNet_model/DECCaTNet_model.py", line 114, in forward
    x = self.projection(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x1960 and 2400x2400)
