Failure # 1 (occurred at 2023-05-25_10-47-32)
[36mray::ImplicitFunc.train()[39m (pid=3386903, ip=129.241.113.29, repr=hyper_search_train)
  File "/lhome/oskarsto/repos/master-eeg-trans/.venv/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 384, in train
    raise skipped from exception_cause(skipped)
  File "/lhome/oskarsto/repos/master-eeg-trans/.venv/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 336, in entrypoint
    return self._trainable_func(
  File "/lhome/oskarsto/repos/master-eeg-trans/.venv/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 653, in _trainable_func
    output = fn()
  File "/lhome/oskarsto/repos/master-eeg-trans/.venv/lib/python3.8/site-packages/ray/tune/trainable/util.py", line 421, in _inner
    return inner(config, checkpoint_dir=None)
  File "/lhome/oskarsto/repos/master-eeg-trans/.venv/lib/python3.8/site-packages/ray/tune/trainable/util.py", line 413, in inner
    return trainable(config, **fn_kwargs)
  File "/lhome/oskarsto/repos/master-eeg-trans/DECCaTNet/DECCaTNet_model/hyper_search.py", line 144, in hyper_search_train
    cf.pre_train_model(copy.deepcopy(all_params), global_params)
  File "/lhome/oskarsto/repos/master-eeg-trans/DECCaTNet/DECCaTNet_model/contrastive_framework.py", line 411, in pre_train_model
    val_loader = torch.utils.data.DataLoader(val_set, batch_size=batch_size, shuffle=shuffle, num_workers=num_workers)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 277, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/sampler.py", line 97, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
